import { BLOCKS } from '../blocks.js'

export default {
  1: {
    x: 0,
    y: 0.2,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {},
  },
  2: {
    x: 0.03,
    y: 0.22,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {},
  },
  3: {
    x: 0.06,
    y: 0.23,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {},
  },
  4: {
    x: 0.1,
    y: 0.26,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_PLANTE_G1': 1,
      'trees/SWAMP_PLANTE_G2': 1,
      'trees/SWAMP_PLANTE_G3': 1,
      'trees/SWAMP_PLANTE_G4': 1,
      'trees/SWAMP_PLANTE_G5': 1,
      'trees/SWAMP_PLANTE_G6': 1,
      'trees/SWAMP_PLANTE_G7': 1,
      void: 50,
    },
  },
  5: {
    x: 0.14,
    y: 0.27,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_PLANTE_G1': 1,
      'trees/SWAMP_PLANTE_G2': 1,
      'trees/SWAMP_PLANTE_G3': 1,
      'trees/SWAMP_PLANTE_G4': 1,
      'trees/SWAMP_PLANTE_G5': 1,
      'trees/SWAMP_PLANTE_G6': 1,
      'trees/SWAMP_PLANTE_G7': 1,
      void: 40,
    },
  },
  6: {
    x: 0.16,
    y: 0.28,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_PLANTE_G1': 1,
      'trees/SWAMP_PLANTE_G2': 1,
      'trees/SWAMP_PLANTE_G3': 1,
      'trees/SWAMP_PLANTE_G4': 1,
      'trees/SWAMP_PLANTE_G5': 1,
      'trees/SWAMP_PLANTE_G6': 1,
      'trees/SWAMP_PLANTE_G7': 1,
      void: 30,
    },
  },
  7: {
    x: 0.18,
    y: 0.29,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  8: {
    x: 0.19,
    y: 0.305,
    type: BLOCKS.MUD,
    subtype: BLOCKS.MUD,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  9: {
    x: 0.23,
    y: 0.31,
    type: BLOCKS.GRASS_SWAMP,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  10: {
    x: 0.31,
    y: 0.31,
    type: BLOCKS.MUD,
    subtype: BLOCKS.MUD,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  11: {
    x: 0.35,
    y: 0.305,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  12: {
    x: 0.36,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_PLANTE_G1': 1,
      'trees/SWAMP_PLANTE_G2': 1,
      'trees/SWAMP_PLANTE_G3': 1,
      'trees/SWAMP_PLANTE_G4': 1,
      'trees/SWAMP_PLANTE_G5': 1,
      'trees/SWAMP_PLANTE_G6': 1,
      'trees/SWAMP_PLANTE_G7': 1,
      void: 30,
    },
  },
  13: {
    x: 0.41,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  14: {
    x: 0.42,
    y: 0.305,
    type: BLOCKS.MUD,
    subtype: BLOCKS.MUD,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  15: {
    x: 0.47,
    y: 0.31,
    type: BLOCKS.GRASS_SWAMP,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  16: {
    x: 0.54,
    y: 0.31,
    type: BLOCKS.MUD,
    subtype: BLOCKS.MUD,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  17: {
    x: 0.59,
    y: 0.305,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  18: {
    x: 0.6,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_PLANTE_G1': 1,
      'trees/SWAMP_PLANTE_G2': 1,
      'trees/SWAMP_PLANTE_G3': 1,
      'trees/SWAMP_PLANTE_G4': 1,
      'trees/SWAMP_PLANTE_G5': 1,
      'trees/SWAMP_PLANTE_G6': 1,
      'trees/SWAMP_PLANTE_G7': 1,
      void: 30,
    },
  },
  19: {
    x: 0.65,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  20: {
    x: 0.66,
    y: 0.305,
    type: BLOCKS.MUD,
    subtype: BLOCKS.MUD,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  21: {
    x: 0.69,
    y: 0.31,
    type: BLOCKS.GRASS_SWAMP,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  22: {
    x: 0.74,
    y: 0.31,
    type: BLOCKS.MUD,
    subtype: BLOCKS.MUD,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  23: {
    x: 0.77,
    y: 0.305,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  24: {
    x: 0.78,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_PLANTE_G1': 1,
      'trees/SWAMP_PLANTE_G2': 1,
      'trees/SWAMP_PLANTE_G3': 1,
      'trees/SWAMP_PLANTE_G4': 1,
      'trees/SWAMP_PLANTE_G5': 1,
      'trees/SWAMP_PLANTE_G6': 1,
      'trees/SWAMP_PLANTE_G7': 1,
      void: 30,
    },
  },
  25: {
    x: 0.83,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  26: {
    x: 0.84,
    y: 0.305,
    type: BLOCKS.MUD,
    subtype: BLOCKS.MUD,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  27: {
    x: 0.87,
    y: 0.31,
    type: BLOCKS.GRASS_SWAMP,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  28: {
    x: 0.92,
    y: 0.31,
    type: BLOCKS.MUD,
    subtype: BLOCKS.MUD,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  29: {
    x: 0.95,
    y: 0.305,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  30: {
    x: 0.96,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/SWAMP_PLANTE_G1': 1,
      'trees/SWAMP_PLANTE_G2': 1,
      'trees/SWAMP_PLANTE_G3': 1,
      'trees/SWAMP_PLANTE_G4': 1,
      'trees/SWAMP_PLANTE_G5': 1,
      'trees/SWAMP_PLANTE_G6': 1,
      'trees/SWAMP_PLANTE_G7': 1,
      void: 30,
    },
  },
  31: {
    x: 1,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {},
  },
}
