export namespace ITEM_CATEGORY {
    let RELIC: string;
    let RUNE: string;
    let MOUNT: string;
    let HAT: string;
    let CLOACK: string;
    let AMULET: string;
    let RING: string;
    let BELT: string;
    let BOOTS: string;
    let TITLE: string;
    let PET: string;
    let BOW: string;
    let WAND: string;
    let STAFF: string;
    let DAGGER: string;
    let SHOVEL: string;
    let SWORD: string;
    let SCYTHE: string;
    let AXE: string;
    let HAMMER: string;
    let FISHING_ROD: string;
    let PICKAXE: string;
    let KEY: string;
    let RESOURCE: string;
    let ORB: string;
    let CHARACTER: string;
}
export const EQUIPMENTS: string[];
export const WEAPONS: string[];
export const MISC: string[];
export const CONSUMABLES: string[];
