declare namespace _default {
    namespace plaine {
        let x: number;
        let y: number;
        let type: string;
        let subtype: string;
        let fadeIn: number;
        let fadeOut: number;
        let flora: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
    }
    namespace cliff_start {
        let x_1: number;
        export { x_1 as x };
        let y_1: number;
        export { y_1 as y };
        let type_1: string;
        export { type_1 as type };
        let subtype_1: string;
        export { subtype_1 as subtype };
        let fadeIn_1: number;
        export { fadeIn_1 as fadeIn };
        let fadeOut_1: number;
        export { fadeOut_1 as fadeOut };
        let flora_1: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
        export { flora_1 as flora };
    }
    namespace cliff_up {
        let x_2: number;
        export { x_2 as x };
        let y_2: number;
        export { y_2 as y };
        let type_2: string;
        export { type_2 as type };
        let subtype_2: string;
        export { subtype_2 as subtype };
        let fadeIn_2: number;
        export { fadeIn_2 as fadeIn };
        let fadeOut_2: number;
        export { fadeOut_2 as fadeOut };
        let flora_2: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
        export { flora_2 as flora };
    }
    namespace cliff_down_start {
        let x_3: number;
        export { x_3 as x };
        let y_3: number;
        export { y_3 as y };
        let type_3: string;
        export { type_3 as type };
        let subtype_3: string;
        export { subtype_3 as subtype };
        let fadeIn_3: number;
        export { fadeIn_3 as fadeIn };
        let fadeOut_3: number;
        export { fadeOut_3 as fadeOut };
        let flora_3: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
        export { flora_3 as flora };
    }
    namespace cliff_down {
        let x_4: number;
        export { x_4 as x };
        let y_4: number;
        export { y_4 as y };
        let type_4: string;
        export { type_4 as type };
        let subtype_4: string;
        export { subtype_4 as subtype };
        let fadeIn_4: number;
        export { fadeIn_4 as fadeIn };
        let fadeOut_4: number;
        export { fadeOut_4 as fadeOut };
        let flora_4: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
        export { flora_4 as flora };
    }
    namespace plaine_2 {
        let x_5: number;
        export { x_5 as x };
        let y_5: number;
        export { y_5 as y };
        let type_5: string;
        export { type_5 as type };
        let subtype_5: string;
        export { subtype_5 as subtype };
        let fadeIn_5: number;
        export { fadeIn_5 as fadeIn };
        let fadeOut_5: number;
        export { fadeOut_5 as fadeOut };
        let flora_5: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
        export { flora_5 as flora };
    }
    namespace cliff_start_2 {
        let x_6: number;
        export { x_6 as x };
        let y_6: number;
        export { y_6 as y };
        let type_6: string;
        export { type_6 as type };
        let subtype_6: string;
        export { subtype_6 as subtype };
        let fadeIn_6: number;
        export { fadeIn_6 as fadeIn };
        let fadeOut_6: number;
        export { fadeOut_6 as fadeOut };
        let flora_6: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
        export { flora_6 as flora };
    }
    namespace cliff_up_2 {
        let x_7: number;
        export { x_7 as x };
        let y_7: number;
        export { y_7 as y };
        let type_7: string;
        export { type_7 as type };
        let subtype_7: string;
        export { subtype_7 as subtype };
        let fadeIn_7: number;
        export { fadeIn_7 as fadeIn };
        let fadeOut_7: number;
        export { fadeOut_7 as fadeOut };
        let flora_7: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
        export { flora_7 as flora };
    }
    namespace cliff_down_start_2 {
        let x_8: number;
        export { x_8 as x };
        let y_8: number;
        export { y_8 as y };
        let type_8: string;
        export { type_8 as type };
        let subtype_8: string;
        export { subtype_8 as subtype };
        let fadeIn_8: number;
        export { fadeIn_8 as fadeIn };
        let fadeOut_8: number;
        export { fadeOut_8 as fadeOut };
        let flora_8: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
        export { flora_8 as flora };
    }
    namespace cliff_down_2 {
        let x_9: number;
        export { x_9 as x };
        let y_9: number;
        export { y_9 as y };
        let type_9: string;
        export { type_9 as type };
        let subtype_9: string;
        export { subtype_9 as subtype };
        let fadeIn_9: number;
        export { fadeIn_9 as fadeIn };
        let fadeOut_9: number;
        export { fadeOut_9 as fadeOut };
        let flora_9: {
            'rocks/GRASSLAND_ROCK_G1': number;
            'rocks/GRASSLAND_ROCK_G2': number;
            'rocks/GRASSLAND_ROCK_G3': number;
            'rocks/GRASSLAND_ROCK_G4': number;
            'rocks/GRASSLAND_ROCK_G5': number;
            'rocks/GRASSLAND_ROCK_G6': number;
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            void: number;
        };
        export { flora_9 as flora };
    }
    namespace plaine_3 {
        let x_10: number;
        export { x_10 as x };
        let y_10: number;
        export { y_10 as y };
        let type_10: string;
        export { type_10 as type };
        let subtype_10: string;
        export { subtype_10 as subtype };
        let fadeIn_10: number;
        export { fadeIn_10 as fadeIn };
        let fadeOut_10: number;
        export { fadeOut_10 as fadeOut };
        let flora_10: {
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            'trees/GRASSLAND_BIG_TREE_G1': number;
            'trees/GRASSLAND_BIG_TREE_G2': number;
            void: number;
        };
        export { flora_10 as flora };
    }
    namespace cliff_start_3 {
        let x_11: number;
        export { x_11 as x };
        let y_11: number;
        export { y_11 as y };
        let type_11: string;
        export { type_11 as type };
        let subtype_11: string;
        export { subtype_11 as subtype };
        let fadeIn_11: number;
        export { fadeIn_11 as fadeIn };
        let fadeOut_11: number;
        export { fadeOut_11 as fadeOut };
        let flora_11: {
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            'trees/GRASSLAND_BIG_TREE_G1': number;
            'trees/GRASSLAND_BIG_TREE_G2': number;
            void: number;
        };
        export { flora_11 as flora };
    }
    namespace cliff_up_3 {
        let x_12: number;
        export { x_12 as x };
        let y_12: number;
        export { y_12 as y };
        let type_12: string;
        export { type_12 as type };
        let subtype_12: string;
        export { subtype_12 as subtype };
        let fadeIn_12: number;
        export { fadeIn_12 as fadeIn };
        let fadeOut_12: number;
        export { fadeOut_12 as fadeOut };
        let flora_12: {
            'trees/GRASSLAND_TREE_G1': number;
            'trees/GRASSLAND_TREE_G2': number;
            'trees/GRASSLAND_TREE_G3': number;
            'trees/GRASSLAND_TREE_G4': number;
            'trees/GRASSLAND_ACACIA_G1': number;
            'trees/GRASSLAND_ACACIA_G2': number;
            'trees/GRASSLAND_ACACIA_G3': number;
            'trees/GRASSLAND_ACACIA_G4': number;
            'trees/GRASSLAND_BIRCH_G1': number;
            'trees/GRASSLAND_BIRCH_G2': number;
            'trees/GRASSLAND_BIRCH_G3': number;
            'trees/GRASSLAND_BIRCH_G4': number;
            'trees/GRASSLAND_BIG_TREE_G1': number;
            'trees/GRASSLAND_BIG_TREE_G2': number;
            void: number;
        };
        export { flora_12 as flora };
    }
}
export default _default;
